In [ ]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [1]:
print("hello world")

hello world


In [2]:
import numpy as np

In [3]:
arr1d =np.array([2,3,4,5,6])
print(arr1d)

[2 3 4 5 6]


In [5]:
arr2d =np.array([[1,2,3],[4,5,6]])
print(arr2d)

[[1 2 3]
 [4 5 6]]


In [6]:
### list ws numpy array

In [7]:
list=[2,3,4,5,6]
print(list)

[2, 3, 4, 5, 6]


In [11]:
### list mltiplication

In [12]:
list =[1,2,3,4,5]
print(list*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [13]:
### multiplicatitiion off array

In [14]:
arr=np.array([2,3,4])
print(arr*2)

[4 6 8]


In [15]:
import time

In [16]:
start=time.time()
list=[i*2 for i in range(10000000)]
print(time.time()-start)

0.47101879119873047


In [18]:
start=time.time()
array=np.arange(10000000)*2
print(time.time()-start)

0.03764653205871582


In [19]:
### creating array from sacratcb

In [ ]:
zeros=np.zeros((3,4))## print zeros
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [21]:
ones=np.ones((2,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
full=np.full((3,3),5)
print(full)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [23]:
randam=np.random.random((2,3))
print(randam)

[[0.03644907 0.05472409 0.06255316]
 [0.81820317 0.76730228 0.20562718]]


In [26]:
sequence = np.arange(1,10,2)
print(sequence)

[1 3 5 7 9]
